Class {
	#name : #GtGemStoneSessionViewModelDeselected,
	#superclass : #Announcement,
	#instVars : [
		'gemStoneSessionViewModel'
	],
	#category : #'GToolkit-GemStone-Pharo-Events'
}

{ #category : #generated }
GtGemStoneSessionViewModelDeselected >> gemStoneSessionViewModel [
	<objectGetter: #session>
	<generatedFrom: #'GtRobocoderMetamodelAnnouncementTemplate>>#objectGetterTemplate'>

	^ gemStoneSessionViewModel
]

{ #category : #generated }
GtGemStoneSessionViewModelDeselected >> gemStoneSessionViewModel: aGemStoneSessionViewModel [
	<objectSetter: #session>
	<generatedFrom: #'GtRobocoderMetamodelAnnouncementTemplate>>#objectSetterTemplate'>

	gemStoneSessionViewModel := aGemStoneSessionViewModel
]
