Class {
	#name : #GtpoGtPhlowColumnedTreeViewSpecification,
	#superclass : #GtpoGtPhlowViewSpecification,
	#traits : 'TGlpoGtPhlowListingViewSpecification + TGlpoGtPhlowTreeViewSpecification',
	#classTraits : 'TGlpoGtPhlowListingViewSpecification classTrait + TGlpoGtPhlowTreeViewSpecification classTrait',
	#category : #'GToolkit-GemStone-Pharo-Proxies'
}

{ #category : #accessing }
GtpoGtPhlowColumnedTreeViewSpecification class >> remoteClassName [
	^ #GtPhlowColumnedTreeViewSpecification
]
