Class {
	#name : #GtpoGtPhlowTreeViewSpecification,
	#superclass : #GtRsrProxyServiceClient,
	#traits : 'TGlpoGtPhlowListingViewSpecification + TGlpoGtPhlowTreeViewSpecification',
	#classTraits : 'TGlpoGtPhlowListingViewSpecification classTrait + TGlpoGtPhlowTreeViewSpecification classTrait',
	#category : #'GToolkit-GemStone-Pharo-Proxies'
}

{ #category : #accessing }
GtpoGtPhlowTreeViewSpecification class >> remoteClassName [
	^ #GtPhlowTreeViewSpecification
]
