Trait {
	#name : #TGlpoGtPhlowTreeViewSpecification,
	#category : #'GToolkit-GemStone-Pharo-Stubs'
}

{ #category : #accessing }
TGlpoGtPhlowTreeViewSpecification >> retrieveChildrenForNodeAtPath: aNodePath [
	^ self
		proxyPerform: #retrieveChildrenForNodeAtPath:
		withArguments: { aNodePath }
]

{ #category : #accessing }
TGlpoGtPhlowTreeViewSpecification >> retriveSentItemAtPath: aNodePath [
	^ self
		proxyPerform: #retriveSentItemAtPath:
		withArguments: { aNodePath }
]
