Class {
	#name : #GtRemotePhlowColumnedListViewBasicContextActionsGemStoneServiceClientExamples,
	#superclass : #GtRemotePhlowColumnedListViewBasicContextActionsGemStoneExamples,
	#category : #'GToolkit-RemoteExamples-GemStone'
}

{ #category : #private }
GtRemotePhlowColumnedListViewBasicContextActionsGemStoneServiceClientExamples >> convertToTargetProxy: anObject [
	^ anObject asGtProxyObject
]
