Class {
	#name : #GtRemotePhlowColumnedTreeViewBasicContextActionsGemStoneServiceClientExamples,
	#superclass : #GtRemotePhlowColumnedTreeViewBasicContextActionsGemStoneExamples,
	#category : #'GToolkit-RemoteExamples-GemStone'
}

{ #category : #private }
GtRemotePhlowColumnedTreeViewBasicContextActionsGemStoneServiceClientExamples >> convertToTargetProxy: anObject [
	^ anObject asGtProxyObject
]
