Class {
	#name : #GtRemoteGemStoneDeclarativeActionsExamples,
	#superclass : #GtRemotePhlowDeclarativeActionsExamples,
	#traits : 'TGtRemoteGemStoneDeclarativePhlowExamples',
	#classTraits : 'TGtRemoteGemStoneDeclarativePhlowExamples classTrait',
	#category : #'GToolkit-RemoteExamples-GemStone'
}

{ #category : #private }
GtRemoteGemStoneDeclarativeActionsExamples >> testInspectableName [
	"Answer the name of the test inspectable class on the remote"

	^ #GtRemotePhlowDeclarativeTestInspectable
]
