Extension { #name : #GtCoderShortcutIds }

{ #category : #'*GToolkit-GemStone-Lepiter' }
GtCoderShortcutIds >> gemStoneBrowseLocalBehaviorShortcutId [
	^ self shortcutIdForIdentifier: #CoderGemStoneBrowseLocalBehavior
]

{ #category : #'*GToolkit-GemStone-Lepiter' }
GtCoderShortcutIds >> gemStoneBrowseLocalImplementorsShortcutId [
	^ self shortcutIdForIdentifier: #CoderGemStoneBrowseLocalImplementors
]

{ #category : #'*GToolkit-GemStone-Lepiter' }
GtCoderShortcutIds >> gemStoneBrowseLocalReferencesShortcutId [
	^ self shortcutIdForIdentifier: #CoderGemStoneBrowseLocalReferences
]
