Class {
	#name : 'GtRsrEvaluatorService',
	#superclass : 'RsrService',
	#instVars : [
		'selfInstance',
		'script'
	],
	#category : 'GToolkit-GemStone-Services'
}

{ #category : 'accessing' }
GtRsrEvaluatorService >> script [

	^ script
]

{ #category : 'accessing' }
GtRsrEvaluatorService >> script: anObject [

	script := anObject
]

{ #category : 'accessing' }
GtRsrEvaluatorService >> selfInstance [

	^ selfInstance
]

{ #category : 'accessing' }
GtRsrEvaluatorService >> selfInstance: anObject [

	selfInstance := anObject
]
